---

# - name: Create directiry for VMs
#   file: "state=directory path=/opt/VMs force=yes mode 0777"
#   become: yes
#   delegate_to: "{{node_host}}"


- name: Install KVM
  apt:
    name:
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
      - cloud-init
    state: present
  become: yes
  delegate_to: "{{node_host}}"

- name: Start/Enabled libvirtd
  systemd: name=libvirtd enabled=yes state=started
  become: yes
  delegate_to: "{{node_host}}"

- name: Check if the libvirt module is loaded
  shell: "lsmod | grep kvm | wc -l"
  become: yes
  delegate_to: "{{node_host}}"
  register: libvirtd_status

- fail:
    msg: "libvirtd not loaded"
  when: libvirtd_status.stdout == '0'
