---

- name: Check if kvm-network bridge exist
  command: virsh net-info kvm-network
  become: yes
  delegate_to: "{{hypervisor_host}}"
  ignore_errors: yes
  register: kvm_net_exist

- name: Create new network
  command: "{{ item }}"
  become: yes
  delegate_to: "{{hypervisor_host}}"
  ignore_errors: yes
  with_items:
    - "virsh net-define /opt/net.xml"
    - "virsh net-start kvm-network"
    - "virsh net-autostart kvm-network"
  when: kvm_net_exist.rc != 0

- name: Check network creation
  command: "virsh net-info kvm-network"
  become: yes
  delegate_to: "{{hypervisor_host}}"
  register: kvm_net_state
  failed_when: kvm_net_state.rc != 0

# ---
# # tasks file for libvirt-net
# - name: Get list of defined networks
#   virt_net:
#     command: list_nets
#   register: netlist

# - name: Show net list 
#   debug:
#     var:
#       netlist

# - name: Deactivate if exists
#   virt_net:
#     command: destroy
#     name: "{{ item.name }}"
#   when: item.name in netlist.list_nets
#   with_items: "{{ networks }}"
#   ignore_errors: yes

# - name: Undefine if exists
#   virt_net:
#     command: undefine
#     name: "{{ item.name }}"
#   when: item.name in netlist.list_nets
#   with_items: "{{ networks }}"

# - name: Create the network
#   virt_net:
#     command: define
#     name: "{{ item.name }}"
#     xml: '{{ lookup("template", "../templates/virt-net.xml.j2") }}'
#   with_items: "{{ networks }}"

# - name: Autostart it
#   virt_net:
#     name: "{{ item.name }}"
#     autostart: 'yes'
#   with_items: "{{ networks }}"

# - name: Enable
#   virt_net: 
#     name: "{{ item.name }}"
#     state: active
#   with_items: "{{ networks }}"
